napster2/napster2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from napster2 import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index),
    url(r'^register/$', views.register),
    url(r'^register/success/$', views.register_success),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^dashboard/$', views.dashboard),
    url(r'^manage/$', views.update_account_info),
    url(r'^update/success/$', views.update_success),
    url(r'^logout/$', views.logout_page),
    url(r'^view_cart/$', views.view_cart),
    url(r'^checkout/$', views.checkout),
    url(r'^checkout/failure/$', views.checkout_failure),
    url(r'^checkout/success/$', views.checkout_success),
    url(r'^demographics/$', views.demographics),
    url(r'^addtracks/$', views.add_tracks),
    url(r'^addtracks/failure/$', views.add_tracks_failure),
    url(r'^addtracks/success/$', views.add_tracks_success),
    url(r'^addtracks/track_exists/$', views.add_tracks_exists),
#    url(r'^manageplaylist', views.manageplaylist),
    url(r'^search/$', views.search),
    url(r'^search_playlists/$', views.search_playlists),
    url(r'^view_MyPlaylist/$', views.view_MyPlaylist),
    url(r'^edit_MyPlaylist/$', views.edit_upl),
    url(r'^playlist_details/$', views.edit_epl),
    #    url(r'^checkout_success', views.checkout_success),
    url(r'^reporting/sales/$', views.sales_reporting),
    url(r'^reporting/inventory/$', views.inventory_reporting),
]

napster2/napster2/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models


class Album(models.Model):
    albumid = models.AutoField(db_column='AlbumId', primary_key=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=160)  # Field name made lowercase.
    artistid = models.ForeignKey('Artist', db_column='ArtistId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Album'


class Applepay(models.Model):
    appleinvoiceid = models.OneToOneField('Invoice', db_column='AppleInvoiceID', primary_key=True)  # Field name made lowercase.
    appleid = models.CharField(db_column='AppleID', max_length=60, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ApplePay'


class Artist(models.Model):
    artistid = models.AutoField(db_column='ArtistId', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=120, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Artist'


class Clips(models.Model):
    clipstrackid = models.OneToOneField('Track', db_column='ClipsTrackId', primary_key=True)  # Field name made lowercase.
    itunesurl = models.CharField(db_column='ItunesURL', max_length=205, blank=True, null=True)  # Field name made lowercase.
    googleurl = models.CharField(db_column='GoogleURL', max_length=205, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Clips'


class Creditcard(models.Model):
    ccinvoiceid = models.OneToOneField('Invoice', db_column='CCInvoiceID', primary_key=True)  # Field name made lowercase.
    ccnum = models.CharField(db_column='CCNum', max_length=60, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CreditCard'


class Customer(models.Model):
    customerid = models.AutoField(db_column='CustomerId', primary_key=True)  # Field name made lowercase.
    supportrepid = models.ForeignKey('Employee', db_column='SupportRepId', blank=True, null=True)  # Field name made lowercase.
    custpersonid = models.ForeignKey('Person', db_column='CustPersonID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Customer'


class Employee(models.Model):
    employeeid = models.AutoField(db_column='EmployeeId', primary_key=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=30, blank=True, null=True)  # Field name made lowercase.
    reportsto = models.ForeignKey('self', db_column='ReportsTo', blank=True, null=True)  # Field name made lowercase.
    birthdate = models.DateTimeField(db_column='BirthDate', blank=True, null=True)  # Field name made lowercase.
    hiredate = models.DateTimeField(db_column='HireDate', blank=True, null=True)  # Field name made lowercase.
    personid = models.ForeignKey('Person', db_column='PersonID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Employee'


class Genre(models.Model):
    genreid = models.AutoField(db_column='GenreId', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=120, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Genre'


class Google(models.Model):
    googleinvoiceid = models.OneToOneField('Invoice', db_column='GoogleInvoiceID', primary_key=True)  # Field name made lowercase.
    googleid = models.CharField(db_column='GoogleID', max_length=60, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Google'


class Invoice(models.Model):
    invoiceid = models.AutoField(db_column='InvoiceId', primary_key=True)  # Field name made lowercase.
    customerid = models.ForeignKey(Customer, db_column='CustomerId')  # Field name made lowercase.
    invoicedate = models.DateTimeField(db_column='InvoiceDate')  # Field name made lowercase.
    billingaddress = models.CharField(db_column='BillingAddress', max_length=70, blank=True, null=True)  # Field name made lowercase.
    billingcity = models.CharField(db_column='BillingCity', max_length=40, blank=True, null=True)  # Field name made lowercase.
    billingstate = models.CharField(db_column='BillingState', max_length=40, blank=True, null=True)  # Field name made lowercase.
    billingcountry = models.CharField(db_column='BillingCountry', max_length=40, blank=True, null=True)  # Field name made lowercase.
    billingpostalcode = models.CharField(db_column='BillingPostalCode', max_length=10, blank=True, null=True)  # Field name made lowercase.
    total = models.DecimalField(db_column='Total', max_digits=10, decimal_places=2)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Invoice'


class Invoiceline(models.Model):
    invoicelineid = models.AutoField(db_column='InvoiceLineId', primary_key=True)  # Field name made lowercase.
    invoiceid = models.ForeignKey(Invoice, db_column='InvoiceId')  # Field name made lowercase.
    trackid = models.ForeignKey('Track', db_column='TrackId')  # Field name made lowercase.
    unitprice = models.DecimalField(db_column='UnitPrice', max_digits=10, decimal_places=2)  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'InvoiceLine'


class Mediatype(models.Model):
    mediatypeid = models.AutoField(db_column='MediaTypeId', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=120, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MediaType'


class Myplaylist(models.Model):
    myplaylistid = models.AutoField(db_column='MyPlaylistID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=45)  # Field name made lowercase.
    customerid = models.ForeignKey(Customer, db_column='CustomerID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MyPlaylist'


class Myplaylisttracks(models.Model):
    myplaylistid = models.ForeignKey(Myplaylist, db_column='MyPlaylistID')  # Field name made lowercase.
    trackid = models.ForeignKey('Track', db_column='TrackID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MyPlaylistTracks'
        unique_together = (('myplaylistid', 'trackid'),)


class Order(models.Model):
    orderid = models.AutoField(db_column='OrderID', primary_key=True)  # Field name made lowercase.
    customerid = models.ForeignKey(Customer, db_column='CustomerID')  # Field name made lowercase.
    playlistmadby = models.CharField(db_column='PlaylistMadBy', max_length=45, blank=True, null=True)  # Field name made lowercase.
    price = models.CharField(db_column='Price', max_length=45, blank=True, null=True)  # Field name made lowercase.
    confirmed = models.CharField(db_column='Confirmed', max_length=1)  # Field name made lowercase.
    dateentered = models.DateField(db_column='DateEntered')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Order'


class Ordercustplaylist(models.Model):
    ordercustid = models.ForeignKey(Order, db_column='OrderCustID')  # Field name made lowercase.
    custplaylistid = models.ForeignKey(Myplaylist, db_column='CustPlaylistID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'OrderCustPlaylist'
        unique_together = (('ordercustid', 'custplaylistid'),)


class Orderempplaylist(models.Model):
    orderempid = models.ForeignKey(Order, db_column='OrderEmpID')  # Field name made lowercase.
    empplaylistid = models.ForeignKey('Playlist', db_column='EmpPlaylistID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'OrderEmpPlaylist'
        unique_together = (('orderempid', 'empplaylistid'),)


class Ordertrack(models.Model):
    orderid = models.ForeignKey(Order, db_column='OrderId')  # Field name made lowercase.
    ordertrackid = models.ForeignKey('Track', db_column='OrderTrackId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'OrderTrack'
        unique_together = (('orderid', 'ordertrackid'),)


class Payment(models.Model):
    paymentid = models.AutoField(db_column='PaymentID', primary_key=True)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=45, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Payment'


class Paypal(models.Model):
    paypalinvoiceid = models.OneToOneField(Invoice, db_column='PaypalInvoiceID', primary_key=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=60, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Paypal'


class Person(models.Model):
    personid = models.AutoField(db_column='PersonID', primary_key=True)  # Field name made lowercase.

napster2/napster2/templates/checkout/checkout.html
{% extends "base.html" %}
{% block title %}Napster 2 Dashboard{% endblock %}
{% block head %}Checkout{% endblock %}
{% block content %}

Confirmation will lead to checkout success. <br />

Please review your order. <br />

Tracks: <br />
{% if track_cart %}
<table border="0">
  {% for tuple in track_cart %}
   <tr><th>
    <form method="post" action=".">{% csrf_token %}
    <input id="id_trackid" value="{{ tuple.0 }}" name="trackid" type="number" style="width:60px" readonly />
    <input id="id_item" maxlength="40" value="{{ tuple.1 }}" name="track" type="text" readonly />
    <input id="id_price" value="${{ tuple.2 }}" name="price" type="text" style="width:60px" readonly />
    </form>
    </td></tr>
  {% endfor %}
</table>
{% else %}
-none-<br />
{% endif %}

User Playlists: <br />
{% if upl_cart %}
<table border="0">
 {% for tuple in upl_cart %}
   <tr><th>
    <form method="post" action=".">{% csrf_token %}
    <input id="id_myplaylistid" value="{{ tuple.0 }}" name="myplaylistid" type="number" style="width:60px" readonly />
    <input id="id_myplaylist" maxlength="40" value="{{ tuple.1 }}" name="myplaylist" type="text" readonly />
    <input id="id_price" value="${{ tuple.2 }}" name="price" type="text" style="width:60px" readonly />
    </form>
    </td></tr>
  {% endfor %}
</table>
{% else %}
-none-<br />
{% endif %}

Staff Picks: <br />
{% if epl_cart %}
<table border="0">
  {% for tuple in epl_cart %}
   <tr><th>
    <form method="post" action=".">{% csrf_token %}
    <input id="id_playlistid" value="{{ tuple.0 }}" name="playlistid" type="number" style="width:60px" readonly />
    <input id="id_playlist" maxlength="40" value="{{ tuple.1 }}" name="playlist" type="text" readonly />
    <input id="id_price" value="${{ tuple.2 }}" name="price" type="text" style="width:60px" readonly />
    </form>
    </td></tr>
  {% endfor %}
</table>
{% else %}
-none-<br />
{% endif %}
<hr />
Total price: ${{ total_price }}
<hr />

{% if show_confirm_button and person.affiliation == "Customer" %}
  <form method="post" action=".">{% csrf_token %}
    {% if person.creditcardnumber != None %}
      <input type="radio" name="payment_type" value="cc"> Credit Card <br />
    {% endif %}
    {% if person.paypalemail != None %}
      <input type="radio" name="payment_type" value="pp"> Paypal <br />
    {% endif %}
    {% if person.googlepayid != None %}
      <input type="radio" name="payment_type" value="gp"> Google Pay <br />
    {% endif %}
    {% if person.applepayid != None %}
      <input type="radio" name="payment_type" value="ap"> Apple Pay <br />
    {% endif %}
      <input type="submit" name="confirm" value="Confirm" />
  </form>
{% endif %}

{% if person.affiliation == "Employee" %}
  Employees cannot check out.
{% elif not show_confirm_button %}
You cannot check out your shopping cart because your information is not updated. Please make sure to update your email, postal code, city, country, and have at least one payment method. 
{% endif %}

{% endblock %}

napster2/napster2/templates/checkout/failure.html
{% extends "base.html" %}
{% block title %}Napster 2 Dashboard{% endblock %}
{% block head %}Checkout{% endblock %}
{% block content %}
Checkout failed. <br />
You have no items in your shopping cart!
{% endblock %}

napster2/napster2/templates/checkout/success.html
{% extends "base.html" %}
{% block title %}Napster 2 Dashboard{% endblock %}
{% block head %}Checkout{% endblock %}
{% block content %}

Checkout success!

{% endblock %}

napster2/napster2/templates/checkout/view_cart.html
{% extends "base.html" %}
{% block title %}Napster 2 Dashboard{% endblock %}
{% block head %}Shopping Cart{% endblock %}
{% block content %}

Tracks: <br />
{% if track_cart %}
<table border="0">
  {% for tuple in track_cart %}
   <tr><th>
    <form method="post" action=".">{% csrf_token %}
    <input id="id_trackid" value="{{ tuple.0 }}" name="trackid" type="number" style="width:60px" readonly />
    <input id="id_item" maxlength="40" value="{{ tuple.1 }}" name="track" type="text" readonly />
    <input id="id_price" value="${{ tuple.2 }}" name="price" type="text" style="width:60px" readonly />
    <input type="submit" name="remove_track" value="Remove From Cart">
    </form>
    </td></tr>
  {% endfor %}
</table>
{% else %}
-none-<br />
{% endif %}

User Playlists: <br />
{% if upl_cart %}
<table border="0">
 {% for tuple in upl_cart %}
   <tr><th>
    <form method="post" action=".">{% csrf_token %}
    <input id="id_myplaylistid" value="{{ tuple.0 }}" name="myplaylistid" type="number" style="width:60px" readonly />
    <input id="id_myplaylist" maxlength="40" value="{{ tuple.1 }}" name="myplaylist" type="text" readonly />
    <input id="id_price" value="${{ tuple.2 }}" name="price" type="text" style="width:60px" readonly />
    <input type="submit" name="remove_myplaylist" value="Remove From Cart">
    </form>
    </td></tr>
  {% endfor %}
</table>
{% else %}
-none-<br />
{% endif %}

Staff Picks: <br />
{% if epl_cart %}
<table border="0">
  {% for tuple in epl_cart %}
   <tr><th>
    <form method="post" action=".">{% csrf_token %}
    <input id="id_playlistid" value="{{ tuple.0 }}" name="playlistid" type="number" style="width:60px" readonly />
    <input id="id_playlist" maxlength="40" value="{{ tuple.1 }}" name="playlist" type="text" readonly />
    <input id="id_price" value="${{ tuple.2 }}" name="price" type="text" style="width:60px" readonly />
    <input type="submit" name="remove_playlist" value="Remove From Cart">
    </form>
    </td></tr>
  {% endfor %}
</table>
{% else %}
-none-<br />
{% endif %}


<form method="post" action=".">{% csrf_token %}
<input type="submit" name="checkout" value="Checkout">
</form>

    
{% endblock %}